/* PRELOADER */
export const PRELOADER_TOGGLE = 'PRELOADER_TOGGLE'

/* TOASTER */
export const TOAST_TOGGLE = 'TOAST_TOGGLE'

/* PRODUCTS */
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'
export const PRODUCTS_TOGGLE = 'PRODUCTS_TOGGLE'